import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Creates `<workspace>/.solarharness/<subdirectory>` and a `.gitignore` of `*` inside `.solarharness`,
 * so Git ignores Solar's generated files in any project without editing the project's own `.gitignore`.
 */
export async function solarDirectory(workspace: string, subdirectory: string): Promise<string> {
  const root = join(workspace, ".solarharness");
  const directory = join(root, subdirectory);
  await mkdir(directory, { recursive: true });
  await writeFile(join(root, ".gitignore"), "# Generated by Solar Harness.\n*\n", { flag: "wx" }).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== "EEXIST") throw error;
  });
  return directory;
}
